FROM node:18-alpine as builder

RUN apk add tzdata \
  && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo Asia/Shanghai > /etc/timezone \
  && apk add ca-certificates \
  && apk del tzdata

WORKDIR /app

COPY package*.json /app/

RUN npm install --registry=https://mirrors.cloud.tencent.com/npm/

COPY . /app

RUN npm run build:test

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

RUN echo "server { \
    listen       80; \
    listen  [::]:80; \
    server_name  localhost; \
    \
    location / { \
      try_files $uri $uri/ /index.html; \
    } \
    \
    error_page   500 502 503 504  /50x.html; \
    location = /50x.html { \
      root   /usr/share/nginx/html; \
    } \
  }" > /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
