const WS_OPERATION_PATHNAME = '/manage/operation';
const WS_STATISTIC_PATHNAME = '/manage/statistic';

const WS_OPERATION_MESSAGE_KEY = 'WS_OPERATION_MESSAGE_KEY';
const WS_STATISTIC_MESSAGE_KEY = 'WS_STATISTIC_MESSAGE_KEY';

module.exports = {
  WS_OPERATION_PATHNAME,
  WS_STATISTIC_PATHNAME,
  WS_OPERATION_MESSAGE_KEY,
  WS_STATISTIC_MESSAGE_KEY,
};
